stages:
  - build
  - deploy-dev
  
docker_build:
  tags:
    - shell
  stage: build
  only:
    refs:
      - master
  script:
    - docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - COMMIT_TIME=$(date +"%Y%m%dT%H%M%S")
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest client
    - docker tag ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest ${CI_REGISTRY}/${CI_PROJECT_PATH}:${COMMIT_TIME}
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:${COMMIT_TIME}
    - echo ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest

deploy_dev:
  tags:
    - shell
  stage: deploy-dev
  only:
    refs:
      - master
  script:
    - echo ${RANCHER_STG_ENDPOINT}'/v3/project/c-q6vf9:p-pbc6w/workload/deployment:tsa:web-validation-frontend?action=redeploy'
    - curl -u ${RANCHER_STG_USER}:${RANCHER_STG_PASS} -X POST -H 'Accept:application/json' -H 'Content-Type:application/json' ${RANCHER_STG_ENDPOINT}'/v3/project/c-q6vf9:p-pbc6w/workload/deployment:tsa:web-validation-frontend?action=redeploy'