version: '3'

services:

  app:
    build: client
    container_name: e-documents-nuxt
    restart: always
    ports:
      - '4000:4000'
    env_file:
      - .env
    command: 'npm run start'

networks:
  default:
    external:
      name:
        microservice_network

  client_network:
    external:
      name: client_network
